apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: teams-alerts
  namespace: todo-app
  labels:
    alertmanagerConfig: teams
spec:
  route:
    receiver: teams-webhook
    matchers:
      - name: alert_source
        value: todo-app
        matchType: "="
    groupBy:
      - alertname
      - namespace
      - component
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h

  receivers:
    - name: teams-webhook
      msteamsv2Configs:
        - webhookURL:
            name: teams-webhook
            key: webhook-url

          title: >-
            {{ if gt (len .Alerts.Firing) 0 }}
            🚨 {{ .CommonLabels.alertname }}
            {{ else }}
            ✅ {{ .CommonLabels.alertname }} Resolved
            {{ end }}

          text: |
            **State:** {{ .Status | toUpper }}
            **Severity:** {{ .CommonLabels.severity }}
            **Servis:** {{ .CommonLabels.component }}
            **Namespace:** {{ .CommonLabels.namespace }}

            {{ if gt (len .Alerts.Firing) 0 }}
            **Active Pods:**
            {{ range .Alerts.Firing }}
            **▶** {{ .Labels.pod }} → **Mem:** **{{ .Annotations.memory_usage }}**
                **  - S:** {{ .StartsAt.Format "02.01.2006 15:04:05" }}
            {{ end }}
            {{ end }}

            {{ if gt (len .Alerts.Resolved) 0 }}
            **Resolved Pods:**
            {{ range .Alerts.Resolved }}
            **▶** {{ .Labels.pod }}
                **  - S:** {{ .StartsAt.Format "02.01.2006 15:04:05" }} **- R: **{{ .EndsAt.Format "02.01.2006 15:04:05" }}
                **  - Time:** {{ humanizeDuration (.EndsAt.Sub .StartsAt) }}

            {{ end }}
            {{ end }}

            **Summary:** {{ .CommonAnnotations.summary }}

            **Description:** {{ .CommonAnnotations.description }}

          sendResolved: true