apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig

metadata:
  name: teams-alerts
  namespace: todo-app
  labels:
    alertmanagerConfig: teams

spec:
  route:
    receiver: teams-webhook

    matchers:
      - name: alert_source
        value: todo-app
        matchType: "="

    groupBy:
      - alertname
      - namespace
      - component

    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h

  receivers:
    - name: teams-webhook
      msteamsv2Configs:
        - webhookURL:
            name: teams-webhook
            key: webhook-url

          title: '{{ if eq .Status "firing" }}🚨 {{ .CommonLabels.alertname }}{{ else }}✅ {{ .CommonLabels.alertname }} Recovered{{ end }}'

          text: |
            **Durum:** {{ .Status | toUpper }}

            **Severity:** {{ .CommonLabels.severity }}
            **Servis:** {{ .CommonLabels.component }}
            **Namespace:** {{ .CommonLabels.namespace }}

            **Etkilenen Podlar:**
            {{ range .Alerts }}
            • {{ .Labels.pod }}
            {{ end }}

            **Özet:** {{ .CommonAnnotations.summary }}

            **Açıklama:** {{ .CommonAnnotations.description }}

          sendResolved: true