namespace: todo-app
config:
  POSTGRES_DB: todo
  POSTGRES_USER: todo_user
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
secret:
  POSTGRES_PASSWORD: todo_password
backend:
  replicas: 1
  image:
    repository: volkandemirors/todo-backend
    tag: "v1.0.0"
  port: 8080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"
backendService:
  port: 8080
  targetPort: 8080
postgres:
  image:
    repository: postgres
    tag: "16"
  port: 5432
  storage: 1Gi
  storageClassName: manual
  hostPath: /mnt/data/postgres
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
postgresPvc:
  storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
postgresDeployment:
  replicas: 1
postgresService:
  port: 5432
  targetPort: 5432
frontend:
  replicas: 1
  image:
    repository: volkandemirors/todo-frontend
    tag: "v2.0.6"
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
frontendService:
  port: 80
  targetPort: 80
  nodePort: 30080
