apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: infra
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/demirorsvolkan/todo-infra.git
    targetRevision: main
    path: argocd
    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ServerSideApply=true