{{- if .Values.backend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: {{ .Values.backend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.backend.autoscaling.maxReplicas }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.backend.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
        - type: Percent
          value: {{ .Values.backend.autoscaling.behavior.scaleUp.percentValue }}
          periodSeconds: {{ .Values.backend.autoscaling.behavior.scaleUp.periodSeconds }}
      selectPolicy: Max

    scaleDown:
      stabilizationWindowSeconds: {{ .Values.backend.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
        - type: Percent
          value: {{ .Values.backend.autoscaling.behavior.scaleDown.percentValue }}
          periodSeconds: {{ .Values.backend.autoscaling.behavior.scaleDown.periodSeconds }}
      selectPolicy: Max

  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
