apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgresService.port }}
      targetPort: {{ .Values.postgresService.targetPort }}
  type: ClusterIP
