apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: todo-app
  namespace: argocd

spec:
  applicationRefs:
    - namePattern: todo-app
      images:
        - alias: backend
          imageName: volkandemirors/todo-backend:v1.0.0
          commonUpdateSettings:
            updateStrategy: semver
            allowTags: "regexp:^v?[0-9]+\\.[0-9]+\\.[0-9]+$"
          manifestTargets:
            helm:
              name: backend.image.repository
              tag: backend.image.tag

        - alias: frontend
          imageName: volkandemirors/todo-frontend:v2.0.3
          commonUpdateSettings:
            updateStrategy: semver
            allowTags: "regexp:^v?[0-9]+\\.[0-9]+\\.[0-9]+$"
          manifestTargets:
            helm:
              name: frontend.image.repository
              tag: frontend.image.tag

      writeBackConfig:
        method: git:secret:git-write-creds
        gitConfig:
          repository: https://github.com/demirorsvolkan/todo-infra.git
          branch: main
          writeBackTarget: helmvalues:./values.yaml
