apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default

  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.12.1
      helm:
        values: |
          persistence:
            defaultClass: true
            defaultClassReplicaCount: 2
            volumeBindingMode: WaitForFirstConsumer

          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule

          defaultSettings:
            taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"

          preUpgradeChecker:
            jobEnabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
